alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: dev.visiblenetworklabs.com
  type: PRIMARY
name: sample-vuejs
region: sfo
services:
- build_command: yarn build
  environment_slug: node-js
  git:
    branch: main
    repo_clone_url: https://github.com/digitalocean/sample-vuejs.git
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: sample-vuejs
  routes:
  - path: /
  run_command: yarn start
  source_dir: /